### ISSUE TITLE
Create a formal list of project requirements

### ISSUE THREAD

**Issue by ardaofluoglu** [swe574-group2/swe574#10]
Create the first version of requirments document.

**Comment by seydakaradag** [comment]
Hocanın out of scope dediği bazı requirementları nice to have şeklinde ekledim.  içeriği geliştirebiliriz.

**Comment by penumbram-zz** [comment]
I've changed the page a bit, switched to MoSCoW prioritisation. "nice to have"s are now divided into 2 sub categories, "could have" and "won't have". I've added some requirements of my own. 

Also, I think we should think about moving the "Requirements Analysis" page into "Requirements" page, by combining them. What do you think @ardaofluoglu @okanmenevseoglu @seydakaradag @gr3ysky @skanca

**Comment by ardaofluoglu** [comment]
I believe questions should not be present in a final and formal requirements page as the requirements document should be as concise, clear, and to-the-point as possible.

If we are to keep them in a separate page, then I think that we should not use subsection numbering like "01.1" in wiki titles as it complicates the appearence.

In SWE573, I had only numbered main wiki pages like formal requirements and design pages, and left out other pages unnumbered; so they appeared at the bottom of the page list.

But again, I am fine with any way and open to your ideas.

@penumbram @okanmenevseoglu @seydakaradag @gr3ysky @skanca

**Comment by seydakaradag** [comment]
I agree with @ardaofluoglu, it would be better not to present the questions in the final requirements, lets keep them in a separete page

**Comment by seydakaradag** [comment]
I have combined  our 2 different requirement pages. Now we have one page. ı have grouped the requirements as requirements by functionality and requirements by priority. These two groups include the same requirements :) what do you think ?
