### ISSUE TITLE
Update the Requirements Page

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#21]
- The requirements must be categorized by functionality. These categories can contain subcategories.
- Won't have requirements don't need to be categorized.
- Specifications must be explained in more detail. (Such as html annotation, what part of html to annotate and etc.)

**Comment by penumbram-zz** [comment]
1) Requirement lar yazılırken Web Annotation Model reference edilmeli, mesela yeni bir annotation girilirken nasıl bir json modeli kullanılacağı belirtilebilir, bunu reference etmek için web annotation model'ı biraz okuyup neleri nasıl yaptığını öğrenmek gerekiyor
2) HTML reference ları olmalı, örneğin target edilirken HTML tag'i olmadan edileceği belirtilmeli, aynı şekilde image annotation'larında img tag leri içindeki image ların annotate edileceği belirtilmeli
3) Bir sayfada kaç target olduğu gösterilmeli
4) Selector kelimesi ambigious, bunun yerine target kullanılmalı (çünkü web annotation model'da selector diye başka bir şey varmış)  
5) Filtering/Paging le ilgili requirement lar olmalı (Bir sayfada 10000 annotation varsa bunların hepsi gönderilemeyeceği için, neye göre filtreleyip göndereceğiz) Paging için de örneğin bu 10000 annotation arasından seçtiğimiz ilk 100'ünü gönderdik, bunu nasıl page edeceğiz, neye dağılacak

**Comment by seydakaradag** [comment]
There should be "filtering" in the requirements. For instance, if a user wants to see only question annotations, the user should be able to see.

Filtering can be multi directional, such as filtering by motivation, date, user.
