### ISSUE TITLE
Decision of the technologies that will be used in the project.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#22]

**Comment by seydakaradag** [comment]
we decided to write the codes with Intellij (https://tr.wikipedia.org/wiki/IntelliJ_IDEA)
We were divided into 2 groups. First group's members are Okan, Tolga and Arda and they are responsible for back-end. The second group members are Şenol, Şeyda and Taner and they are responsible for front- end.

**Comment by ardaofluoglu** [comment]
All settled
