### ISSUE TITLE
Update the sequence diagrams.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#24]
The sequence diagrams shall be updated to explain the system interaction in more detail. For example; the "text" that will be annotated shall be given in detail such as an "html target". Someone that has no idea of the system should be able to clearly understand what can be done in the system.

**Comment by seydakaradag** [comment]
There should be design details (target, body etc.) in the sequence diagrams. "Choosing target", "create body", "to show the targets as image" should be shown in the sequence diagrams.
