### ISSUE TITLE
Update the project plan.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#26]
1) Project plan should be given in more detail with assignees for each task.
2) Some estimations should be corrected. (Such as; 12 days for authentication will be shortened.)
3) Date for delivery should be updated. (Major things should be done in the middle of December.)

**Comment by ardaofluoglu** [comment]
Project delivery date should be 15th of December.
After that, user manual can be prepared.
Authorization implementation time is revised.
