### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by penumbram-zz** [swe574-group2/swe574#36]
- Add Documentation sub (throughout the project)

**Comment by uskudarli** [comment]
I think I am not on your project planning issue.

**Comment by penumbram-zz** [comment]
Yeah I fat fingered, sorry.

**Comment by uskudarli** [comment]
np

**Comment by ardaofluoglu** [comment]
Updated the project plan by adding sections for user guide, features, known bugs, and deployment
