### ISSUE TITLE
Finalize Endpoints on the Annotation Server.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#60]
There are many missing endpoints that needs to be implemented. A list will be added.

**Comment by seydakaradag** [comment]
![img-20161204-wa0013](https://cloud.githubusercontent.com/assets/14984710/20867470/aa35ac38-ba4d-11e6-9331-313d4d153b16.jpg)

Hi,

We created our manage page. Please consider the search criterieas on this page when you define the endpoints.

**Comment by okanmenevseoglu** [comment]
Mostly done, will review on Saturday.

**Comment by okanmenevseoglu** [comment]
Done.
