### ISSUE TITLE
Error on intellij

### ISSUE THREAD

**Issue by seydakaradag** [swe574-group2/swe574#62]
Hi guys,

I re-installed intellij idea and tried to make  configurations to run server but I had following error message. I searched on the internet and did what I read but they didn't work. Any idea? @okanmenevseoglu @ardaofluoglu @penumbram 
![img-20161203-wa0010](https://cloud.githubusercontent.com/assets/14984710/20861610/f67947fa-b99c-11e6-82f3-5f1dd132c1ea.jpeg)

**Comment by okanmenevseoglu** [comment]
Problem is solved via TeamViewer.

**Comment by seydakaradag** [comment]
I took a video while Okan was working with  my computer. available upon request  :)    👍
