### ISSUE TITLE
Deploy project.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#70]
Project should  be deployed on an web server instance.

**Comment by penumbram-zz** [comment]
Currently, changes concerning the deployment are on the [deploy branch](https://github.com/swe574-group2/swe574/tree/deploy). @ardaofluoglu

**Comment by okanmenevseoglu** [comment]
We have successfully deployed the project on: ec2-35-165-112-121.us-west-2.compute.amazonaws.com:8080
