### ISSUE TITLE
Search for annotations is not working

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#74]
I created 2 annotations on https://medium.com/@lancegpowelljr/social-vr-and-the-2016-presidential-debate-68a78e73b3d9#.g22g3d252 : 1 text and 1 image, both have the string "Plaza" in their body.

When I search for "Plaza" I do not see any results.

**Comment by okanmenevseoglu** [comment]
This is also related to dynamic link issue #73
