### ISSUE TITLE
The details of an annotation can not be viewed.

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#75]
When I see an annotation on the side bar, there is no way for me to expand and see more details - i.e. motivations. 

Also, there is no function to the (1) number that appears next to target text.

**Comment by uskudarli** [comment]
It would be nice to see other details, but it is okay like this. 

For example, if it is a question, or explanation, etc. 

So no need to fix.

**Comment by penumbram-zz** [comment]
@uskudarli I can add the motivation to the panel on the right, are you sure it's okay?

**Comment by uskudarli** [comment]
If you are going to change, you may add the "translation" motivation :)

It would be good to see the motivation.

**Comment by penumbram-zz** [comment]
It should be done. The following image shows how we display the tags. Also, the translation tag is now available. 😃 

<img width="282" alt="screen shot 2017-01-07 at 22 24 31" src="https://cloud.githubusercontent.com/assets/8571749/21744504/a6ee3544-d51f-11e6-915c-74164e5b8b2b.png">

**Comment by uskudarli** [comment]
Cool.  Reloaded and saw it.

Nice to have good progress :)

**Comment by penumbram-zz** [comment]
Cool, so I'm closing this issue. 😃  Feel free to reopen if something related to it seems off.

**Comment by gr3ysky** [comment]
thanks for the effort @penumbram

**Comment by gr3ysky** [comment]
I have also added this enhancement for search results and groups as well.
