### ISSUE TITLE
Created annotations do not persist

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#76]
I have created annotations on the same page. After I close the side panel the annotations are gone. Says there are (0) annotations.

This is a very serious bug!

Annotations must persist in accordance with the protocol.

**Comment by penumbram-zz** [comment]
I believe this is related with [#73](https://github.com/swe574-group2/swe574/issues/73).
I've checked it with [this](http://www.hurriyet.com.tr/meteorolojiden-son-dakika-uyarisibalkanlardan-geliyor-en-kuvvetli-kar-yagisi-40327013) and the annotations seem to persist when the URL is not dynamic. I will investigate further.
