### ISSUE TITLE
geek mode is not implemented

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#77]
We can not see the annotations in JSON-LD format. Difficult to verify.

Where is your annotation store? Please send details so I can examine them,

**Comment by okanmenevseoglu** [comment]
@uskudarli You can use "Postman" to view our database. I will try to explain it briefly with the easiest way:
![2017-01-06](https://cloud.githubusercontent.com/assets/15822551/21725214/1eb08ff4-d440-11e6-9865-d5abf38fad3d.png)
**STEPS**
**1)** You should choose post request and enter the following AWS link.
**2)** You should enter a pageSize and pageNumber on the body to get the any size or page you wanted.
**3)** After you send your request, it should return all the public annotations on the DB by the size and page you entered.
**4)** You can search here with your source (the page link) to view the annotation.

**Comment by uskudarli** [comment]
I will try to look at it after I brave my way home in the snow now.

Thanks.

Will let you know either way how it goes.

Thanks

--s

ps. I tried postman earilier, but must have goofed something.

**Comment by uskudarli** [comment]
I am able to see the annotations.

I am not able to interpret all the "null" values. Can you enlighten me?

**Comment by uskudarli** [comment]
I have fed the annotations to the validator. There are some fails, did you validate them?

**Comment by okanmenevseoglu** [comment]
@uskudarli We have "null" values because our annotation model on the server side is wider than the requirements for this version. They can be used in future versions but for now you can basically ignore them. And which annotation validator did you use? If you can send us, we can check.

**Comment by uskudarli** [comment]
The issue is that not all fields are valid at all times. In other words
some attributes are context dependedn.

So, putting an attribute and equating it to null may not be ok. Example the
source attribute. Therefore, attributes that make sense should be generated
for a given attribute. Read the model for "source" attribute for example.

The time values are invalid. They should be dateTime format,
i.e. "2016-01-03T11:00:00Z"

I have mentioned and shared the validator several times. Here it is again:
http://w3c-test.org/annotation-model/annotations/annotationMusts-manual.html

I believe some annotations are just left in the system from earlier trials.
For example, some seem not to have "@context".

Kind regards
-s
