### ISSUE TITLE
When selecting text or image the plugin window doesn't show up

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#78]
According to documentation, when I select text or image, the annotation window should popup. It does not. Instead, I have to click on the extension icon. Instead of add annotation page, I see the search. There is a link there that says "show annotations". By selecting that I can reach the add annotation side bar.

It is very confusing.

**Comment by penumbram-zz** [comment]
@uskudarli I'll be fixing it

**Comment by uskudarli** [comment]
If I look at the test cases in your report, I see the steps and expected results. These explanations suggest that it should popup as such. I will try to test as soon as I find the time.

**Comment by uskudarli** [comment]
My tests are going better. The UI is a bit goofy, but I am getting the hang of it. Maybe I will fix it ;)

**Comment by okanmenevseoglu** [comment]
@uskudarli Is there a problem now with this issue?

**Comment by uskudarli** [comment]
i think we are okay now
