### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#80]
I have never been able to get any results from search

I will give one example:

page: http://mitan.in/bcp/raika/

Search:

Search for: biocultural

Start date: 2016-01-01
End date: 2016-01-07

I get:

Search results for 'biocultural'

although we have:

{
      "id": "http://mitan.in/bcp/raika/",
      "type": "Annotation",
      "motivation": "describing",
      "creator": {
        "id": null,
        "type": null,
        "name": "suzy",
        "nickname": "suzy"
      },
      "created": 1483729255000,
      "generator": {
        "id": "MyGeneratorId",
        "type": null,
        "name": "CatPlugin",
        "homePage": "www.catplugin.net"
      },
      "stylesheet": null,
      "body": {
        "id": "http://example.org/body44",
        "type": null,
        "purpose": "describing",
        "value": "Raika focuses on **biocultural** values with emphasis on livestock, traditional knowledge and pastoral life.",
        "format": null,
        "language": null,
        "source": {
          "id": null,
          "type": null,
          "format": null,
          "language": "en",
          "creator": null
        }
      },
...
    }

**Comment by okanmenevseoglu** [comment]
@uskudarli From your given info: "End date: 2016-01-07"
It should be 2017.

**Comment by uskudarli** [comment]
:)

tnx

**Comment by okanmenevseoglu** [comment]
@uskudarli You are welcome. :)
